### ISSUE TITLE
Cert manager deprecation

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/terraform-ibm-cert-manager#5]
When you provision a certificate manager instance you get a deprecation warning:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/974294/163466218-cdec6f67-f41b-4fd0-a55a-b3906dfdf0a9.png">

> IBM Cloud Certificate Manager is deprecated. You will be able to continue working as normal until 30 September 2022. At that time you will no longer be able to create new instances of the service and the tile will be removed from the catalog. On 31 December 2022, support for the service will be removed and any existing instances will be deleted.

The guidance suggests to use Secrets Manager instead of Certificate Manager: https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-migrate-from-certificate-manager

Secrets manager is in the IBM Cloud Catalog at: https://cloud.ibm.com/catalog/services/secrets-manager

**Comment by rich-ehrhardt** [comment]
Secrets manager module has been created to replace this,
https://github.com/cloud-native-toolkit/terraform-ibm-secrets-manager
